name: sketchide
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.11 # Scope Storage path
  flutter_native_splash: ^2.4.2 # Splash Screen
  logging: ^1.2.0 # file serve
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1
  change_app_package_name: ^1.4.0

flutter_icons: # Moved outside of the 'flutter' section
  android: true
  ios: true
  image_path: "assets/icon.png" # Path to your main icon image

flutter:
  uses-material-design: true
